/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Attendance: () => import('#controllers/admin/attendance_controller'),
    Category: () => import('#controllers/admin/category_controller'),
    Company: () => import('#controllers/admin/company_controller'),
    DailyReport: () => import('#controllers/admin/daily_report_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    Employee: () => import('#controllers/admin/employee_controller'),
    Holiday: () => import('#controllers/admin/holiday_controller'),
    Leave: () => import('#controllers/admin/leave_controller'),
    Report: () => import('#controllers/admin/report_controller'),
    Salary: () => import('#controllers/admin/salary_controller'),
    SubCategory: () => import('#controllers/admin/sub_category_controller'),
    Task: () => import('#controllers/admin/task_controller'),
  },
  Auth: () => import('#controllers/auth_controller'),
  employee: {
    Attendance: () => import('#controllers/employee/attendance_controller'),
    Dashboard: () => import('#controllers/employee/dashboard_controller'),
    IdCard: () => import('#controllers/employee/id_card_controller'),
    Leave: () => import('#controllers/employee/leave_controller'),
    Profile: () => import('#controllers/employee/profile_controller'),
    Salary: () => import('#controllers/employee/salary_controller'),
    Task: () => import('#controllers/employee/task_controller'),
  },
  lead: {
    Lead: () => import('#controllers/lead/lead_controller'),
  },
  Notification: () => import('#controllers/notification_controller'),
}
