/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InsuranceCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = InsuranceCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InsuranceCompanySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'name', 'subCategoryId', 'updatedAt'] as const
  $columns = InsuranceCompanySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare subCategoryId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InsuranceSubCategorySchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'deletedAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = InsuranceSubCategorySchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TaskManagementSchema extends BaseModel {
  static $columns = ['assignBy', 'assignTo', 'callResponse', 'clientContactNumber', 'clientName', 'conversionStatus', 'createdAt', 'deletedAt', 'flowAmount', 'flowComment', 'flowDateTime', 'followUpDate', 'id', 'insuranceCategoryId', 'insuranceCompanyId', 'insuranceSubCategoryId', 'insuranceType', 'isActive', 'leadDate', 'notRespondedAction', 'priority', 'referenceName', 'registrationNumber', 'renewalDate', 'respondedOption', 'status', 'taskAction', 'updatedAt', 'userId'] as const
  $columns = TaskManagementSchema.$columns
  @column()
  declare assignBy: bigint | number | null
  @column()
  declare assignTo: bigint | number | null
  @column()
  declare callResponse: string | null
  @column()
  declare clientContactNumber: string | null
  @column()
  declare clientName: string | null
  @column()
  declare conversionStatus: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare flowAmount: string | null
  @column()
  declare flowComment: string | null
  @column.dateTime()
  declare flowDateTime: DateTime | null
  @column.date()
  declare followUpDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare insuranceCategoryId: number | null
  @column()
  declare insuranceCompanyId: number | null
  @column()
  declare insuranceSubCategoryId: number | null
  @column()
  declare insuranceType: string | null
  @column()
  declare isActive: boolean | null
  @column.date()
  declare leadDate: DateTime | null
  @column()
  declare notRespondedAction: string | null
  @column()
  declare priority: string | null
  @column()
  declare referenceName: string | null
  @column()
  declare registrationNumber: string | null
  @column.date()
  declare renewalDate: DateTime | null
  @column()
  declare respondedOption: string | null
  @column()
  declare status: string | null
  @column()
  declare taskAction: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'designation', 'dob', 'doj', 'email', 'id', 'ip', 'isActive', 'isEmailVerified', 'isMobileVerified', 'latitude', 'longitude', 'mobile', 'name', 'password', 'plainPassword', 'role', 'salary', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare designation: string | null
  @column.date()
  declare dob: DateTime | null
  @column.date()
  declare doj: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare ip: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare isEmailVerified: boolean | null
  @column()
  declare isMobileVerified: boolean | null
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare mobile: string | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare plainPassword: string | null
  @column()
  declare role: string
  @column()
  declare salary: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
