/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.test_redis': {
    methods: ["GET","HEAD"],
    pattern: '/api/test-redis',
    tokens: [{"old":"/api/test-redis","type":0,"val":"api","end":""},{"old":"/api/test-redis","type":0,"val":"test-redis","end":""}],
    types: placeholder as Registry['auth.test_redis']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/login',
    tokens: [{"old":"/api/login","type":0,"val":"api","end":""},{"old":"/api/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.logout': {
    methods: ["POST"],
    pattern: '/api/logout',
    tokens: [{"old":"/api/logout","type":0,"val":"api","end":""},{"old":"/api/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'employee.store': {
    methods: ["POST"],
    pattern: '/api/employees',
    tokens: [{"old":"/api/employees","type":0,"val":"api","end":""},{"old":"/api/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['employee.store']['types'],
  },
  'employee.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees',
    tokens: [{"old":"/api/employees","type":0,"val":"api","end":""},{"old":"/api/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['employee.index']['types'],
  },
  'employee.list': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/list',
    tokens: [{"old":"/api/employees/list","type":0,"val":"api","end":""},{"old":"/api/employees/list","type":0,"val":"employees","end":""},{"old":"/api/employees/list","type":0,"val":"list","end":""}],
    types: placeholder as Registry['employee.list']['types'],
  },
  'employee.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee.show']['types'],
  },
  'employee.update': {
    methods: ["PUT"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee.update']['types'],
  },
  'employee.destroy': {
    methods: ["DELETE"],
    pattern: '/api/employees/:id',
    tokens: [{"old":"/api/employees/:id","type":0,"val":"api","end":""},{"old":"/api/employees/:id","type":0,"val":"employees","end":""},{"old":"/api/employees/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee.destroy']['types'],
  },
  'employee.check': {
    methods: ["GET","HEAD"],
    pattern: '/api/check',
    tokens: [{"old":"/api/check","type":0,"val":"api","end":""},{"old":"/api/check","type":0,"val":"check","end":""}],
    types: placeholder as Registry['employee.check']['types'],
  },
  'category.store': {
    methods: ["POST"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['category.store']['types'],
  },
  'category.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['category.index']['types'],
  },
  'category.active': {
    methods: ["GET","HEAD"],
    pattern: '/api/categories/active',
    tokens: [{"old":"/api/categories/active","type":0,"val":"api","end":""},{"old":"/api/categories/active","type":0,"val":"categories","end":""},{"old":"/api/categories/active","type":0,"val":"active","end":""}],
    types: placeholder as Registry['category.active']['types'],
  },
  'category.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['category.show']['types'],
  },
  'category.update': {
    methods: ["PUT"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['category.update']['types'],
  },
  'category.destroy': {
    methods: ["DELETE"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['category.destroy']['types'],
  },
  'sub_category.store': {
    methods: ["POST"],
    pattern: '/api/sub-categories',
    tokens: [{"old":"/api/sub-categories","type":0,"val":"api","end":""},{"old":"/api/sub-categories","type":0,"val":"sub-categories","end":""}],
    types: placeholder as Registry['sub_category.store']['types'],
  },
  'sub_category.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/sub-categories',
    tokens: [{"old":"/api/sub-categories","type":0,"val":"api","end":""},{"old":"/api/sub-categories","type":0,"val":"sub-categories","end":""}],
    types: placeholder as Registry['sub_category.index']['types'],
  },
  'sub_category.get_by_category': {
    methods: ["GET","HEAD"],
    pattern: '/api/sub-categories/by-category/:categoryId',
    tokens: [{"old":"/api/sub-categories/by-category/:categoryId","type":0,"val":"api","end":""},{"old":"/api/sub-categories/by-category/:categoryId","type":0,"val":"sub-categories","end":""},{"old":"/api/sub-categories/by-category/:categoryId","type":0,"val":"by-category","end":""},{"old":"/api/sub-categories/by-category/:categoryId","type":1,"val":"categoryId","end":""}],
    types: placeholder as Registry['sub_category.get_by_category']['types'],
  },
  'sub_category.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/sub-categories/:id',
    tokens: [{"old":"/api/sub-categories/:id","type":0,"val":"api","end":""},{"old":"/api/sub-categories/:id","type":0,"val":"sub-categories","end":""},{"old":"/api/sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sub_category.show']['types'],
  },
  'sub_category.update': {
    methods: ["PUT"],
    pattern: '/api/sub-categories/:id',
    tokens: [{"old":"/api/sub-categories/:id","type":0,"val":"api","end":""},{"old":"/api/sub-categories/:id","type":0,"val":"sub-categories","end":""},{"old":"/api/sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sub_category.update']['types'],
  },
  'sub_category.destroy': {
    methods: ["DELETE"],
    pattern: '/api/sub-categories/:id',
    tokens: [{"old":"/api/sub-categories/:id","type":0,"val":"api","end":""},{"old":"/api/sub-categories/:id","type":0,"val":"sub-categories","end":""},{"old":"/api/sub-categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sub_category.destroy']['types'],
  },
  'company.store': {
    methods: ["POST"],
    pattern: '/api/companies',
    tokens: [{"old":"/api/companies","type":0,"val":"api","end":""},{"old":"/api/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['company.store']['types'],
  },
  'company.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/companies',
    tokens: [{"old":"/api/companies","type":0,"val":"api","end":""},{"old":"/api/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['company.index']['types'],
  },
  'company.get_by_sub_category': {
    methods: ["GET","HEAD"],
    pattern: '/api/companies/by-sub-category/:subCategoryId',
    tokens: [{"old":"/api/companies/by-sub-category/:subCategoryId","type":0,"val":"api","end":""},{"old":"/api/companies/by-sub-category/:subCategoryId","type":0,"val":"companies","end":""},{"old":"/api/companies/by-sub-category/:subCategoryId","type":0,"val":"by-sub-category","end":""},{"old":"/api/companies/by-sub-category/:subCategoryId","type":1,"val":"subCategoryId","end":""}],
    types: placeholder as Registry['company.get_by_sub_category']['types'],
  },
  'company.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/companies/:id',
    tokens: [{"old":"/api/companies/:id","type":0,"val":"api","end":""},{"old":"/api/companies/:id","type":0,"val":"companies","end":""},{"old":"/api/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['company.show']['types'],
  },
  'company.update': {
    methods: ["PUT"],
    pattern: '/api/companies/:id',
    tokens: [{"old":"/api/companies/:id","type":0,"val":"api","end":""},{"old":"/api/companies/:id","type":0,"val":"companies","end":""},{"old":"/api/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['company.update']['types'],
  },
  'company.destroy': {
    methods: ["DELETE"],
    pattern: '/api/companies/:id',
    tokens: [{"old":"/api/companies/:id","type":0,"val":"api","end":""},{"old":"/api/companies/:id","type":0,"val":"companies","end":""},{"old":"/api/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['company.destroy']['types'],
  },
  'task.store': {
    methods: ["POST"],
    pattern: '/api/tasks',
    tokens: [{"old":"/api/tasks","type":0,"val":"api","end":""},{"old":"/api/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['task.store']['types'],
  },
  'task.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks',
    tokens: [{"old":"/api/tasks","type":0,"val":"api","end":""},{"old":"/api/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['task.index']['types'],
  },
  'task.get_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/:id/logs',
    tokens: [{"old":"/api/tasks/:id/logs","type":0,"val":"api","end":""},{"old":"/api/tasks/:id/logs","type":0,"val":"tasks","end":""},{"old":"/api/tasks/:id/logs","type":1,"val":"id","end":""},{"old":"/api/tasks/:id/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['task.get_logs']['types'],
  },
  'task.renewal': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/renewal',
    tokens: [{"old":"/api/tasks/renewal","type":0,"val":"api","end":""},{"old":"/api/tasks/renewal","type":0,"val":"tasks","end":""},{"old":"/api/tasks/renewal","type":0,"val":"renewal","end":""}],
    types: placeholder as Registry['task.renewal']['types'],
  },
  'task.update_renewal': {
    methods: ["PUT"],
    pattern: '/api/tasks/renewal/:id',
    tokens: [{"old":"/api/tasks/renewal/:id","type":0,"val":"api","end":""},{"old":"/api/tasks/renewal/:id","type":0,"val":"tasks","end":""},{"old":"/api/tasks/renewal/:id","type":0,"val":"renewal","end":""},{"old":"/api/tasks/renewal/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['task.update_renewal']['types'],
  },
  'task.search': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/search',
    tokens: [{"old":"/api/tasks/search","type":0,"val":"api","end":""},{"old":"/api/tasks/search","type":0,"val":"tasks","end":""},{"old":"/api/tasks/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['task.search']['types'],
  },
  'task.filter': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/filter',
    tokens: [{"old":"/api/tasks/filter","type":0,"val":"api","end":""},{"old":"/api/tasks/filter","type":0,"val":"tasks","end":""},{"old":"/api/tasks/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['task.filter']['types'],
  },
  'task.counts': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/counts',
    tokens: [{"old":"/api/tasks/counts","type":0,"val":"api","end":""},{"old":"/api/tasks/counts","type":0,"val":"tasks","end":""},{"old":"/api/tasks/counts","type":0,"val":"counts","end":""}],
    types: placeholder as Registry['task.counts']['types'],
  },
  'task.export_excel': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/export-excel',
    tokens: [{"old":"/api/tasks/export-excel","type":0,"val":"api","end":""},{"old":"/api/tasks/export-excel","type":0,"val":"tasks","end":""},{"old":"/api/tasks/export-excel","type":0,"val":"export-excel","end":""}],
    types: placeholder as Registry['task.export_excel']['types'],
  },
  'task.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/tasks/:id',
    tokens: [{"old":"/api/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['task.show']['types'],
  },
  'task.update': {
    methods: ["PUT"],
    pattern: '/api/tasks/:id',
    tokens: [{"old":"/api/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['task.update']['types'],
  },
  'task.destroy': {
    methods: ["DELETE"],
    pattern: '/api/tasks/:id',
    tokens: [{"old":"/api/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['task.destroy']['types'],
  },
  'task.change_status': {
    methods: ["PATCH"],
    pattern: '/api/tasks/:id/status',
    tokens: [{"old":"/api/tasks/:id/status","type":0,"val":"api","end":""},{"old":"/api/tasks/:id/status","type":0,"val":"tasks","end":""},{"old":"/api/tasks/:id/status","type":1,"val":"id","end":""},{"old":"/api/tasks/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['task.change_status']['types'],
  },
  'task.reassign': {
    methods: ["POST"],
    pattern: '/api/tasks/reassign',
    tokens: [{"old":"/api/tasks/reassign","type":0,"val":"api","end":""},{"old":"/api/tasks/reassign","type":0,"val":"tasks","end":""},{"old":"/api/tasks/reassign","type":0,"val":"reassign","end":""}],
    types: placeholder as Registry['task.reassign']['types'],
  },
  'admin_attendance.complete_dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/dashboard/complete',
    tokens: [{"old":"/api/admin/attendance/dashboard/complete","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/dashboard/complete","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/dashboard/complete","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/dashboard/complete","type":0,"val":"dashboard","end":""},{"old":"/api/admin/attendance/dashboard/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['admin_attendance.complete_dashboard']['types'],
  },
  'admin_attendance.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/dashboard',
    tokens: [{"old":"/api/admin/attendance/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/dashboard","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin_attendance.dashboard']['types'],
  },
  'admin_attendance.get_requests': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/requests',
    tokens: [{"old":"/api/admin/attendance/requests","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/requests","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/requests","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['admin_attendance.get_requests']['types'],
  },
  'admin_attendance.handle_request': {
    methods: ["PUT"],
    pattern: '/api/admin/attendance/request/:id',
    tokens: [{"old":"/api/admin/attendance/request/:id","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/request/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/request/:id","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/request/:id","type":0,"val":"request","end":""},{"old":"/api/admin/attendance/request/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_attendance.handle_request']['types'],
  },
  'admin_attendance.report': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/report',
    tokens: [{"old":"/api/admin/attendance/report","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/report","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/report","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['admin_attendance.report']['types'],
  },
  'admin_attendance.get_settings': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/settings',
    tokens: [{"old":"/api/admin/attendance/settings","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin_attendance.get_settings']['types'],
  },
  'admin_attendance.update_settings': {
    methods: ["PUT"],
    pattern: '/api/admin/attendance/settings',
    tokens: [{"old":"/api/admin/attendance/settings","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['admin_attendance.update_settings']['types'],
  },
  'admin_attendance.filter_monthly_attendance': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/filter',
    tokens: [{"old":"/api/admin/attendance/filter","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/filter","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/filter","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['admin_attendance.filter_monthly_attendance']['types'],
  },
  'admin_attendance.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance',
    tokens: [{"old":"/api/admin/attendance","type":0,"val":"api","end":""},{"old":"/api/admin/attendance","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance","type":0,"val":"attendance","end":""}],
    types: placeholder as Registry['admin_attendance.index']['types'],
  },
  'admin_attendance.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/attendance/:id',
    tokens: [{"old":"/api/admin/attendance/:id","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_attendance.show']['types'],
  },
  'admin_attendance.update': {
    methods: ["PUT"],
    pattern: '/api/admin/attendance/:id',
    tokens: [{"old":"/api/admin/attendance/:id","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_attendance.update']['types'],
  },
  'admin_attendance.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/attendance/:id',
    tokens: [{"old":"/api/admin/attendance/:id","type":0,"val":"api","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/attendance/:id","type":0,"val":"attendance","end":""},{"old":"/api/admin/attendance/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_attendance.destroy']['types'],
  },
  'employee_task.store': {
    methods: ["POST"],
    pattern: '/api/employee/tasks',
    tokens: [{"old":"/api/employee/tasks","type":0,"val":"api","end":""},{"old":"/api/employee/tasks","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['employee_task.store']['types'],
  },
  'employee_task.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks',
    tokens: [{"old":"/api/employee/tasks","type":0,"val":"api","end":""},{"old":"/api/employee/tasks","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks","type":0,"val":"tasks","end":""}],
    types: placeholder as Registry['employee_task.index']['types'],
  },
  'employee_task.renewal': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/renewal',
    tokens: [{"old":"/api/employee/tasks/renewal","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/renewal","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/renewal","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/renewal","type":0,"val":"renewal","end":""}],
    types: placeholder as Registry['employee_task.renewal']['types'],
  },
  'employee_task.update_renewal': {
    methods: ["PUT"],
    pattern: '/api/employee/tasks/renewal/:id',
    tokens: [{"old":"/api/employee/tasks/renewal/:id","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/renewal/:id","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/renewal/:id","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/renewal/:id","type":0,"val":"renewal","end":""},{"old":"/api/employee/tasks/renewal/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_task.update_renewal']['types'],
  },
  'employee_task.search': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/search',
    tokens: [{"old":"/api/employee/tasks/search","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/search","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/search","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['employee_task.search']['types'],
  },
  'employee_task.filter': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/filter',
    tokens: [{"old":"/api/employee/tasks/filter","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/filter","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/filter","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['employee_task.filter']['types'],
  },
  'employee_task.counts': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/counts',
    tokens: [{"old":"/api/employee/tasks/counts","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/counts","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/counts","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/counts","type":0,"val":"counts","end":""}],
    types: placeholder as Registry['employee_task.counts']['types'],
  },
  'employee_task.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/stats',
    tokens: [{"old":"/api/employee/tasks/stats","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/stats","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/stats","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['employee_task.stats']['types'],
  },
  'employee_task.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/tasks/:id',
    tokens: [{"old":"/api/employee/tasks/:id","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/:id","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/:id","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_task.show']['types'],
  },
  'employee_task.update_status': {
    methods: ["PUT"],
    pattern: '/api/employee/tasks/:id/status',
    tokens: [{"old":"/api/employee/tasks/:id/status","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/:id/status","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/:id/status","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/:id/status","type":1,"val":"id","end":""},{"old":"/api/employee/tasks/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['employee_task.update_status']['types'],
  },
  'employee_task.update_workflow': {
    methods: ["PUT"],
    pattern: '/api/employee/tasks/:id/workflow',
    tokens: [{"old":"/api/employee/tasks/:id/workflow","type":0,"val":"api","end":""},{"old":"/api/employee/tasks/:id/workflow","type":0,"val":"employee","end":""},{"old":"/api/employee/tasks/:id/workflow","type":0,"val":"tasks","end":""},{"old":"/api/employee/tasks/:id/workflow","type":1,"val":"id","end":""},{"old":"/api/employee/tasks/:id/workflow","type":0,"val":"workflow","end":""}],
    types: placeholder as Registry['employee_task.update_workflow']['types'],
  },
  'employee_attendance.check_in': {
    methods: ["POST"],
    pattern: '/api/employee/attendance/check-in',
    tokens: [{"old":"/api/employee/attendance/check-in","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/check-in","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/check-in","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/check-in","type":0,"val":"check-in","end":""}],
    types: placeholder as Registry['employee_attendance.check_in']['types'],
  },
  'employee_attendance.check_out': {
    methods: ["POST"],
    pattern: '/api/employee/attendance/check-out',
    tokens: [{"old":"/api/employee/attendance/check-out","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/check-out","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/check-out","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/check-out","type":0,"val":"check-out","end":""}],
    types: placeholder as Registry['employee_attendance.check_out']['types'],
  },
  'employee_attendance.location_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/location-status',
    tokens: [{"old":"/api/employee/attendance/location-status","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/location-status","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/location-status","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/location-status","type":0,"val":"location-status","end":""}],
    types: placeholder as Registry['employee_attendance.location_status']['types'],
  },
  'employee_attendance.today': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/today',
    tokens: [{"old":"/api/employee/attendance/today","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/today","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/today","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/today","type":0,"val":"today","end":""}],
    types: placeholder as Registry['employee_attendance.today']['types'],
  },
  'employee_attendance.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/history',
    tokens: [{"old":"/api/employee/attendance/history","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/history","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/history","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['employee_attendance.history']['types'],
  },
  'employee_attendance.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/summary',
    tokens: [{"old":"/api/employee/attendance/summary","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/summary","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/summary","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['employee_attendance.summary']['types'],
  },
  'employee_attendance.create_request': {
    methods: ["POST"],
    pattern: '/api/employee/attendance/request',
    tokens: [{"old":"/api/employee/attendance/request","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/request","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/request","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['employee_attendance.create_request']['types'],
  },
  'employee_attendance.get_requests': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/requests',
    tokens: [{"old":"/api/employee/attendance/requests","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/requests","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/requests","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['employee_attendance.get_requests']['types'],
  },
  'employee_attendance.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/attendance/:id',
    tokens: [{"old":"/api/employee/attendance/:id","type":0,"val":"api","end":""},{"old":"/api/employee/attendance/:id","type":0,"val":"employee","end":""},{"old":"/api/employee/attendance/:id","type":0,"val":"attendance","end":""},{"old":"/api/employee/attendance/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_attendance.show']['types'],
  },
  'employee_leave.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/leaves/dashboard',
    tokens: [{"old":"/api/employee/leaves/dashboard","type":0,"val":"api","end":""},{"old":"/api/employee/leaves/dashboard","type":0,"val":"employee","end":""},{"old":"/api/employee/leaves/dashboard","type":0,"val":"leaves","end":""},{"old":"/api/employee/leaves/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['employee_leave.dashboard']['types'],
  },
  'employee_leave.create_request': {
    methods: ["POST"],
    pattern: '/api/employee/leaves/request',
    tokens: [{"old":"/api/employee/leaves/request","type":0,"val":"api","end":""},{"old":"/api/employee/leaves/request","type":0,"val":"employee","end":""},{"old":"/api/employee/leaves/request","type":0,"val":"leaves","end":""},{"old":"/api/employee/leaves/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['employee_leave.create_request']['types'],
  },
  'employee_leave.cancel_request': {
    methods: ["DELETE"],
    pattern: '/api/employee/leaves/request/:id',
    tokens: [{"old":"/api/employee/leaves/request/:id","type":0,"val":"api","end":""},{"old":"/api/employee/leaves/request/:id","type":0,"val":"employee","end":""},{"old":"/api/employee/leaves/request/:id","type":0,"val":"leaves","end":""},{"old":"/api/employee/leaves/request/:id","type":0,"val":"request","end":""},{"old":"/api/employee/leaves/request/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['employee_leave.cancel_request']['types'],
  },
  'admin_leave.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/leaves/dashboard',
    tokens: [{"old":"/api/admin/leaves/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/dashboard","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin_leave.dashboard']['types'],
  },
  'admin_leave.get_employees': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/leaves/employees',
    tokens: [{"old":"/api/admin/leaves/employees","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/employees","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/employees","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['admin_leave.get_employees']['types'],
  },
  'admin_leave.assign_leave': {
    methods: ["POST"],
    pattern: '/api/admin/leaves/assign',
    tokens: [{"old":"/api/admin/leaves/assign","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/assign","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/assign","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/assign","type":0,"val":"assign","end":""}],
    types: placeholder as Registry['admin_leave.assign_leave']['types'],
  },
  'admin_leave.create_or_update_balance': {
    methods: ["POST"],
    pattern: '/api/admin/leaves/balance',
    tokens: [{"old":"/api/admin/leaves/balance","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/balance","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/balance","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/balance","type":0,"val":"balance","end":""}],
    types: placeholder as Registry['admin_leave.create_or_update_balance']['types'],
  },
  'admin_leave.get_employee_balance': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/leaves/balance/:employeeId',
    tokens: [{"old":"/api/admin/leaves/balance/:employeeId","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/balance/:employeeId","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/balance/:employeeId","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/balance/:employeeId","type":0,"val":"balance","end":""},{"old":"/api/admin/leaves/balance/:employeeId","type":1,"val":"employeeId","end":""}],
    types: placeholder as Registry['admin_leave.get_employee_balance']['types'],
  },
  'admin_leave.delete_balance': {
    methods: ["DELETE"],
    pattern: '/api/admin/leaves/balance/:id',
    tokens: [{"old":"/api/admin/leaves/balance/:id","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/balance/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/balance/:id","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/balance/:id","type":0,"val":"balance","end":""},{"old":"/api/admin/leaves/balance/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_leave.delete_balance']['types'],
  },
  'admin_leave.reset_balances': {
    methods: ["POST"],
    pattern: '/api/admin/leaves/balance/reset',
    tokens: [{"old":"/api/admin/leaves/balance/reset","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/balance/reset","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/balance/reset","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/balance/reset","type":0,"val":"balance","end":""},{"old":"/api/admin/leaves/balance/reset","type":0,"val":"reset","end":""}],
    types: placeholder as Registry['admin_leave.reset_balances']['types'],
  },
  'admin_leave.handle_request': {
    methods: ["PUT"],
    pattern: '/api/admin/leaves/request/:id',
    tokens: [{"old":"/api/admin/leaves/request/:id","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/request/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/request/:id","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/request/:id","type":0,"val":"request","end":""},{"old":"/api/admin/leaves/request/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_leave.handle_request']['types'],
  },
  'admin_leave.get_types': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/leaves/types',
    tokens: [{"old":"/api/admin/leaves/types","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"types","end":""}],
    types: placeholder as Registry['admin_leave.get_types']['types'],
  },
  'admin_leave.update_type': {
    methods: ["POST"],
    pattern: '/api/admin/leaves/types',
    tokens: [{"old":"/api/admin/leaves/types","type":0,"val":"api","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"admin","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"leaves","end":""},{"old":"/api/admin/leaves/types","type":0,"val":"types","end":""}],
    types: placeholder as Registry['admin_leave.update_type']['types'],
  },
  'lead.get_telesales_employees': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/telesales-employees',
    tokens: [{"old":"/api/leads/telesales-employees","type":0,"val":"api","end":""},{"old":"/api/leads/telesales-employees","type":0,"val":"leads","end":""},{"old":"/api/leads/telesales-employees","type":0,"val":"telesales-employees","end":""}],
    types: placeholder as Registry['lead.get_telesales_employees']['types'],
  },
  'lead.create_lead': {
    methods: ["POST"],
    pattern: '/api/leads',
    tokens: [{"old":"/api/leads","type":0,"val":"api","end":""},{"old":"/api/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['lead.create_lead']['types'],
  },
  'report.employee_performance': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/reports/employee-performance',
    tokens: [{"old":"/api/admin/reports/employee-performance","type":0,"val":"api","end":""},{"old":"/api/admin/reports/employee-performance","type":0,"val":"admin","end":""},{"old":"/api/admin/reports/employee-performance","type":0,"val":"reports","end":""},{"old":"/api/admin/reports/employee-performance","type":0,"val":"employee-performance","end":""}],
    types: placeholder as Registry['report.employee_performance']['types'],
  },
  'report.export': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/reports/export',
    tokens: [{"old":"/api/admin/reports/export","type":0,"val":"api","end":""},{"old":"/api/admin/reports/export","type":0,"val":"admin","end":""},{"old":"/api/admin/reports/export","type":0,"val":"reports","end":""},{"old":"/api/admin/reports/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['report.export']['types'],
  },
  'salary.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/salary/dashboard',
    tokens: [{"old":"/api/admin/salary/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/salary/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/dashboard","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['salary.dashboard']['types'],
  },
  'salary.generate': {
    methods: ["POST"],
    pattern: '/api/admin/salary/generate',
    tokens: [{"old":"/api/admin/salary/generate","type":0,"val":"api","end":""},{"old":"/api/admin/salary/generate","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/generate","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['salary.generate']['types'],
  },
  'salary.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/salary/:employeeId',
    tokens: [{"old":"/api/admin/salary/:employeeId","type":0,"val":"api","end":""},{"old":"/api/admin/salary/:employeeId","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/:employeeId","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/:employeeId","type":1,"val":"employeeId","end":""}],
    types: placeholder as Registry['salary.show']['types'],
  },
  'salary.update_status': {
    methods: ["PUT"],
    pattern: '/api/admin/salary/:id/status',
    tokens: [{"old":"/api/admin/salary/:id/status","type":0,"val":"api","end":""},{"old":"/api/admin/salary/:id/status","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/:id/status","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/:id/status","type":1,"val":"id","end":""},{"old":"/api/admin/salary/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['salary.update_status']['types'],
  },
  'salary.seed': {
    methods: ["POST"],
    pattern: '/api/admin/salary/seed',
    tokens: [{"old":"/api/admin/salary/seed","type":0,"val":"api","end":""},{"old":"/api/admin/salary/seed","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/seed","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/seed","type":0,"val":"seed","end":""}],
    types: placeholder as Registry['salary.seed']['types'],
  },
  'salary.create_structure': {
    methods: ["POST"],
    pattern: '/api/admin/salary-structure',
    tokens: [{"old":"/api/admin/salary-structure","type":0,"val":"api","end":""},{"old":"/api/admin/salary-structure","type":0,"val":"admin","end":""},{"old":"/api/admin/salary-structure","type":0,"val":"salary-structure","end":""}],
    types: placeholder as Registry['salary.create_structure']['types'],
  },
  'salary.get_structures': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/salary-structure',
    tokens: [{"old":"/api/admin/salary-structure","type":0,"val":"api","end":""},{"old":"/api/admin/salary-structure","type":0,"val":"admin","end":""},{"old":"/api/admin/salary-structure","type":0,"val":"salary-structure","end":""}],
    types: placeholder as Registry['salary.get_structures']['types'],
  },
  'salary.get_structure': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/salary-structure/:employeeId',
    tokens: [{"old":"/api/admin/salary-structure/:employeeId","type":0,"val":"api","end":""},{"old":"/api/admin/salary-structure/:employeeId","type":0,"val":"admin","end":""},{"old":"/api/admin/salary-structure/:employeeId","type":0,"val":"salary-structure","end":""},{"old":"/api/admin/salary-structure/:employeeId","type":1,"val":"employeeId","end":""}],
    types: placeholder as Registry['salary.get_structure']['types'],
  },
  'salary.update_structure': {
    methods: ["PUT"],
    pattern: '/api/admin/salary-structure/:id',
    tokens: [{"old":"/api/admin/salary-structure/:id","type":0,"val":"api","end":""},{"old":"/api/admin/salary-structure/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/salary-structure/:id","type":0,"val":"salary-structure","end":""},{"old":"/api/admin/salary-structure/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['salary.update_structure']['types'],
  },
  'salary.delete_structure': {
    methods: ["DELETE"],
    pattern: '/api/admin/salary-structure/:id',
    tokens: [{"old":"/api/admin/salary-structure/:id","type":0,"val":"api","end":""},{"old":"/api/admin/salary-structure/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/salary-structure/:id","type":0,"val":"salary-structure","end":""},{"old":"/api/admin/salary-structure/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['salary.delete_structure']['types'],
  },
  'salary.get_incentive_rules': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/salary/incentive-rules/:employeeId',
    tokens: [{"old":"/api/admin/salary/incentive-rules/:employeeId","type":0,"val":"api","end":""},{"old":"/api/admin/salary/incentive-rules/:employeeId","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/incentive-rules/:employeeId","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/incentive-rules/:employeeId","type":0,"val":"incentive-rules","end":""},{"old":"/api/admin/salary/incentive-rules/:employeeId","type":1,"val":"employeeId","end":""}],
    types: placeholder as Registry['salary.get_incentive_rules']['types'],
  },
  'salary.upsert_incentive_rule': {
    methods: ["POST"],
    pattern: '/api/admin/salary/incentive-rules',
    tokens: [{"old":"/api/admin/salary/incentive-rules","type":0,"val":"api","end":""},{"old":"/api/admin/salary/incentive-rules","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/incentive-rules","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/incentive-rules","type":0,"val":"incentive-rules","end":""}],
    types: placeholder as Registry['salary.upsert_incentive_rule']['types'],
  },
  'salary.delete_incentive_rule': {
    methods: ["DELETE"],
    pattern: '/api/admin/salary/incentive-rules/:id',
    tokens: [{"old":"/api/admin/salary/incentive-rules/:id","type":0,"val":"api","end":""},{"old":"/api/admin/salary/incentive-rules/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/incentive-rules/:id","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/incentive-rules/:id","type":0,"val":"incentive-rules","end":""},{"old":"/api/admin/salary/incentive-rules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['salary.delete_incentive_rule']['types'],
  },
  'salary.bulk_create_incentive_rules': {
    methods: ["POST"],
    pattern: '/api/admin/salary/incentive-rules/bulk',
    tokens: [{"old":"/api/admin/salary/incentive-rules/bulk","type":0,"val":"api","end":""},{"old":"/api/admin/salary/incentive-rules/bulk","type":0,"val":"admin","end":""},{"old":"/api/admin/salary/incentive-rules/bulk","type":0,"val":"salary","end":""},{"old":"/api/admin/salary/incentive-rules/bulk","type":0,"val":"incentive-rules","end":""},{"old":"/api/admin/salary/incentive-rules/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['salary.bulk_create_incentive_rules']['types'],
  },
  'admin_dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/dashboard',
    tokens: [{"old":"/api/admin/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin_dashboard.index']['types'],
  },
  'employee_dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/dashboard',
    tokens: [{"old":"/api/employee/dashboard","type":0,"val":"api","end":""},{"old":"/api/employee/dashboard","type":0,"val":"employee","end":""},{"old":"/api/employee/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['employee_dashboard.index']['types'],
  },
  'employee_salary.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/salary/dashboard',
    tokens: [{"old":"/api/employee/salary/dashboard","type":0,"val":"api","end":""},{"old":"/api/employee/salary/dashboard","type":0,"val":"employee","end":""},{"old":"/api/employee/salary/dashboard","type":0,"val":"salary","end":""},{"old":"/api/employee/salary/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['employee_salary.dashboard']['types'],
  },
  'employee_salary.get_by_month': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/salary/month',
    tokens: [{"old":"/api/employee/salary/month","type":0,"val":"api","end":""},{"old":"/api/employee/salary/month","type":0,"val":"employee","end":""},{"old":"/api/employee/salary/month","type":0,"val":"salary","end":""},{"old":"/api/employee/salary/month","type":0,"val":"month","end":""}],
    types: placeholder as Registry['employee_salary.get_by_month']['types'],
  },
  'employee_salary.breakdown': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/salary/breakdown',
    tokens: [{"old":"/api/employee/salary/breakdown","type":0,"val":"api","end":""},{"old":"/api/employee/salary/breakdown","type":0,"val":"employee","end":""},{"old":"/api/employee/salary/breakdown","type":0,"val":"salary","end":""},{"old":"/api/employee/salary/breakdown","type":0,"val":"breakdown","end":""}],
    types: placeholder as Registry['employee_salary.breakdown']['types'],
  },
  'employee_salary.payslip': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/salary/payslip/:month/:year',
    tokens: [{"old":"/api/employee/salary/payslip/:month/:year","type":0,"val":"api","end":""},{"old":"/api/employee/salary/payslip/:month/:year","type":0,"val":"employee","end":""},{"old":"/api/employee/salary/payslip/:month/:year","type":0,"val":"salary","end":""},{"old":"/api/employee/salary/payslip/:month/:year","type":0,"val":"payslip","end":""},{"old":"/api/employee/salary/payslip/:month/:year","type":1,"val":"month","end":""},{"old":"/api/employee/salary/payslip/:month/:year","type":1,"val":"year","end":""}],
    types: placeholder as Registry['employee_salary.payslip']['types'],
  },
  'employee_salary.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/salary/stats',
    tokens: [{"old":"/api/employee/salary/stats","type":0,"val":"api","end":""},{"old":"/api/employee/salary/stats","type":0,"val":"employee","end":""},{"old":"/api/employee/salary/stats","type":0,"val":"salary","end":""},{"old":"/api/employee/salary/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['employee_salary.stats']['types'],
  },
  'admin_holiday.calendar': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/holidays/calendar',
    tokens: [{"old":"/api/admin/holidays/calendar","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/calendar","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/calendar","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/calendar","type":0,"val":"calendar","end":""}],
    types: placeholder as Registry['admin_holiday.calendar']['types'],
  },
  'admin_holiday.check': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/holidays/check',
    tokens: [{"old":"/api/admin/holidays/check","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/check","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/check","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/check","type":0,"val":"check","end":""}],
    types: placeholder as Registry['admin_holiday.check']['types'],
  },
  'admin_holiday.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/holidays',
    tokens: [{"old":"/api/admin/holidays","type":0,"val":"api","end":""},{"old":"/api/admin/holidays","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['admin_holiday.index']['types'],
  },
  'admin_holiday.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/holidays/:id',
    tokens: [{"old":"/api/admin/holidays/:id","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_holiday.show']['types'],
  },
  'admin_holiday.store': {
    methods: ["POST"],
    pattern: '/api/admin/holidays',
    tokens: [{"old":"/api/admin/holidays","type":0,"val":"api","end":""},{"old":"/api/admin/holidays","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays","type":0,"val":"holidays","end":""}],
    types: placeholder as Registry['admin_holiday.store']['types'],
  },
  'admin_holiday.update': {
    methods: ["PUT"],
    pattern: '/api/admin/holidays/:id',
    tokens: [{"old":"/api/admin/holidays/:id","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_holiday.update']['types'],
  },
  'admin_holiday.destroy': {
    methods: ["DELETE"],
    pattern: '/api/admin/holidays/:id',
    tokens: [{"old":"/api/admin/holidays/:id","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/:id","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin_holiday.destroy']['types'],
  },
  'admin_holiday.bulk_store': {
    methods: ["POST"],
    pattern: '/api/admin/holidays/bulk',
    tokens: [{"old":"/api/admin/holidays/bulk","type":0,"val":"api","end":""},{"old":"/api/admin/holidays/bulk","type":0,"val":"admin","end":""},{"old":"/api/admin/holidays/bulk","type":0,"val":"holidays","end":""},{"old":"/api/admin/holidays/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['admin_holiday.bulk_store']['types'],
  },
  'employee_id_card.download': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/id-card/download',
    tokens: [{"old":"/api/employee/id-card/download","type":0,"val":"api","end":""},{"old":"/api/employee/id-card/download","type":0,"val":"employee","end":""},{"old":"/api/employee/id-card/download","type":0,"val":"id-card","end":""},{"old":"/api/employee/id-card/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['employee_id_card.download']['types'],
  },
  'employee_id_card.view': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/id-card/view',
    tokens: [{"old":"/api/employee/id-card/view","type":0,"val":"api","end":""},{"old":"/api/employee/id-card/view","type":0,"val":"employee","end":""},{"old":"/api/employee/id-card/view","type":0,"val":"id-card","end":""},{"old":"/api/employee/id-card/view","type":0,"val":"view","end":""}],
    types: placeholder as Registry['employee_id_card.view']['types'],
  },
  'employee_id_card.qr_code': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/qr-code',
    tokens: [{"old":"/api/employee/qr-code","type":0,"val":"api","end":""},{"old":"/api/employee/qr-code","type":0,"val":"employee","end":""},{"old":"/api/employee/qr-code","type":0,"val":"qr-code","end":""}],
    types: placeholder as Registry['employee_id_card.qr_code']['types'],
  },
  'employee_id_card.verify': {
    methods: ["POST"],
    pattern: '/api/employee/verify-qr',
    tokens: [{"old":"/api/employee/verify-qr","type":0,"val":"api","end":""},{"old":"/api/employee/verify-qr","type":0,"val":"employee","end":""},{"old":"/api/employee/verify-qr","type":0,"val":"verify-qr","end":""}],
    types: placeholder as Registry['employee_id_card.verify']['types'],
  },
  'daily_report.get_data': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/daily-report/data',
    tokens: [{"old":"/api/admin/daily-report/data","type":0,"val":"api","end":""},{"old":"/api/admin/daily-report/data","type":0,"val":"admin","end":""},{"old":"/api/admin/daily-report/data","type":0,"val":"daily-report","end":""},{"old":"/api/admin/daily-report/data","type":0,"val":"data","end":""}],
    types: placeholder as Registry['daily_report.get_data']['types'],
  },
  'daily_report.generate_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/daily-report/pdf',
    tokens: [{"old":"/api/admin/daily-report/pdf","type":0,"val":"api","end":""},{"old":"/api/admin/daily-report/pdf","type":0,"val":"admin","end":""},{"old":"/api/admin/daily-report/pdf","type":0,"val":"daily-report","end":""},{"old":"/api/admin/daily-report/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['daily_report.generate_pdf']['types'],
  },
  'daily_report.view_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/daily-report/view',
    tokens: [{"old":"/api/admin/daily-report/view","type":0,"val":"api","end":""},{"old":"/api/admin/daily-report/view","type":0,"val":"admin","end":""},{"old":"/api/admin/daily-report/view","type":0,"val":"daily-report","end":""},{"old":"/api/admin/daily-report/view","type":0,"val":"view","end":""}],
    types: placeholder as Registry['daily_report.view_pdf']['types'],
  },
  'daily_report.get_employees': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/daily-report/employees',
    tokens: [{"old":"/api/admin/daily-report/employees","type":0,"val":"api","end":""},{"old":"/api/admin/daily-report/employees","type":0,"val":"admin","end":""},{"old":"/api/admin/daily-report/employees","type":0,"val":"daily-report","end":""},{"old":"/api/admin/daily-report/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['daily_report.get_employees']['types'],
  },
  'employee_profile.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/employee/profile',
    tokens: [{"old":"/api/employee/profile","type":0,"val":"api","end":""},{"old":"/api/employee/profile","type":0,"val":"employee","end":""},{"old":"/api/employee/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['employee_profile.index']['types'],
  },
  'notification.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notification.index']['types'],
  },
  'notification.mark_all_as_read': {
    methods: ["PATCH"],
    pattern: '/api/notifications/mark-all-read',
    tokens: [{"old":"/api/notifications/mark-all-read","type":0,"val":"api","end":""},{"old":"/api/notifications/mark-all-read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/mark-all-read","type":0,"val":"mark-all-read","end":""}],
    types: placeholder as Registry['notification.mark_all_as_read']['types'],
  },
  'notification.mark_one_as_read': {
    methods: ["PATCH"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notification.mark_one_as_read']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
